export const items = [
  {
    productId: 1,
    imgName: 'coffee-bag.png',
    productTitle: "Dark Roast Espresso",
    productTitleForeign: "深色烤浓咖啡",
    origin: "Columbia",
    price: "$96.00",
  },
  {
    productId: 2,
    imgName: 'coffee-bag.png',
    productTitle: "Dark Roast Espresso",
    productTitleForeign: "深色烤浓咖啡",
    origin: "Columbia",
    price: "$96.00",
  },
  {
    productId: 3,
    imgName: 'coffee-bag.png',
    productTitle: "Dark Roast Espresso",
    productTitleForeign: "深色烤浓咖啡",
    origin: "Columbia",
    price: "$96.00",
  },
  {
    productId: 4,
    imgName: 'coffee-bag.png',
    productTitle: "Dark Roast Espresso",
    productTitleForeign: "深色烤浓咖啡",
    origin: "Columbia",
    price: "$96.00",
  },
  {
    productId: 5,
    imgName: 'coffee-bag.png',
    productTitle: "Dark Roast Espresso",
    productTitleForeign: "深色烤浓咖啡",
    origin: "Columbia",
    price: "$96.00",
  },
  {
    productId: 6,
    imgName: 'coffee-bag.png',
    productTitle: "Dark Roast Espresso",
    productTitleForeign: "深色烤浓咖啡",
    origin: "Columbia",
    price: "$96.00",
  },
];