export const ALERT = {
  REMOVE: 'ALERT_REMOVE',
  SET: 'ALERT_SET'
}

export const USER = {
  REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  REGISTER_FAIL: 'USER_REGISTER_FAIL',
  LOADED: 'USER_LOADED',
  AUTH_ERROR: 'USER_AUTH_ERROR',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAIL: 'USER_LOGIN_FAIL',
  LOGOUT: 'USER_LOGOUT',
}

