export const ALERT = {
  REMOVE: 'ALERT_REMOVE',
  SET: 'ALERT_SET',
}

export const BLINK = {
  REMOVE: 'BLINK_REMOVE',
  SET: 'BLINK_SET',
}

export const USER = {
  REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  REGISTER_FAIL: 'USER_REGISTER_FAIL',
  LOADED: 'USER_LOADED',
  AUTH_ERROR: 'USER_AUTH_ERROR',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAIL: 'USER_LOGIN_FAIL',
  LOGOUT: 'USER_LOGOUT',
}

export const STORE = {
  CREATE: 'STORE_CREATE',
  LOAD_ALL: 'STORE_LOAD_ALL',
  LOAD_ONE: 'STORE_LOAD_ONE',
  DELETE: 'STORE_DELETE',
  UPDATE: 'STORE_UPDATE',
  ERROR: 'STORE_ERROR',
}

export const PRODUCT = {
  CREATE: 'PRODUCT_CREATE',
  CREATE_FT: 'PRODUCT_CREATE_FT',
  LOAD_ALL: 'PRODUCT_LOAD_ALL',
  LOAD_ALL_FT: 'PRODUCT_LOAD_ALL_FEATURED',
  LOAD_AMOUNT:'PRODUCT_LOAD_AMOUNT',
  LOAD_ONE: 'PRODUCT_LOAD_ONE',
  DELETE: 'PRODUCT_DELETE',
  UPDATE: 'PRODUCT_UPDATE',
  ERROR: 'PRODUCT_ERROR',
}

export const ARTICLE = {
  CREATE: 'ARTICLE_CREATE',
  CREATE_FEATURED: 'ARTICLE_CREATE_FEATURED',
  CREATE_INTRO: 'ARTICLE_CREATE_INTRO',
  LOAD_ALL: 'ARTICLE_LOAD_ALL',
  GET_ALL_FEATURED: 'ARTICLE_GET_ALL_FEATURED',
  LOAD_ALL_FEATURED: 'ARTICLE_LOAD_ALL_FEATURED',
  LOAD_ALL_INTRO: 'ARTICLE_LOAD_ALL_INTRO',
  LOAD_ONE: 'ARTICLE_LOAD_ONE',
  DELETE: 'ARTICLE_DELETE',
  UPDATE: 'ARTICLE_UPDATE',
  ERROR: 'ARTICLE_ERROR',
}

export const CART = {
  ADD: 'CART_ITEM_ADD',
  CHECKOUT: 'CART_CHECKOUT',
  DELETE: 'CART_ITEM_DELETE',
  UPDATE: 'CART_UPDATE',
  CREATE: 'CART_CREATE',
  ERROR: 'CART_ERROR',
  SELL: 'CART_SELL',
  SOLD: 'CART_SOLD',
}

